# Dependencies
markdown:         redcarpet
highlighter:      rouge

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Ebionics
tagline:          'A Jekyll theme'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      'The Engineering Bionics lab develops technologies that will shape the future of the interaction of human and artificial systems. We conduct inter-disciplinary research across neural engineering, artificial intelligence, robotics, neuroscience, and medicine. We study physiological signals, such as electromyogram (EMG), electroencephalogram (EEG) and electrocardiogram (ECG), extracting useful information such as motion intentions, sensory processing, emotional states and cognitive processing. Specifically, we are working on non-invasive brain-computer interfaces, affordable intelligent thought-controlled prosthetics and mobile ECG solutions.Specifically, we are working on non-invasive brain-computer interfaces, affordable intelligent thought-controlled prosthetics and mobile ECG solutions. Specifically, we work on non-invasive Brain-Computer Interfaces (BCI), affordable intelligent thought-controlled prosthetics, and mobile ECG solutions.'
url:              http://uwebionics.github.io
baseurl:          /
include:         ['_pages']

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/uwebionics/uwebionics.github.io

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
