# Dependencies
markdown:         redcarpet
highlighter:      rouge

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Ebionics
tagline:          'A Jekyll theme'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      'A Univeristy of Waterloo lab, whos research is focused on EEG, EMG, ECG in conjunction with AI. 1 or 2 line statement about lab'
url:              http://uwebionics.github.io
baseurl:          /
include:         ['_pages']

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/uwebionics/uwebionics.github.io

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
